### ISSUE TITLE
Feature: override USER defined in image

### ISSUE THREAD

**Issue by atemate** [neuro-inc/neuro-cli#2013]
When we run images that we don't have access to, it's a big problem when we can't overwrite Dockerfile's instruction `USER` when running a job (both neuro and neuro-flow). Some instruments can't work with storage mounted as `root` whereas their `USER` in Dockerfile is non-root.

**Comment by YevheniiSemendiak** [comment]
As a step further, we could think of mounting the volumes with the ownership of the specified `USER`.

**Comment by dalazx** [comment]
@artem-yushkovsky given the issues with mount permissions, should we just force `root` in this case? one issue I see is that a container can still change the user in run time. wdyt?

**Comment by asvetlov** [comment]
Sorry, I don't follow what is the exact proposal?

**Comment by artem-yushkovsky** [comment]
> should we just force root in this case

I thought about it, it'll be a hotfix, but it should be optional -- some images that require non-root USER will stop working.


> Sorry, I don't follow what is the exact proposal?

- `neuro run --user root ...`
- `neuro run --user web-http ...`

**Comment by mariyadavydova** [comment]
We agreed on the following problem statement and possible solution:
Problem: 
* Oftentimes, NFS is configured by cloud providers in a way, that only `root` has access to files. 
* Also, our storage creates folders under the `root` account, which makes them inaccessible by other users from within the Docker container.
Possible solution:
* We can try to use `fs-group` functionality of K8s to make all FS content accessible by all users belonging to this group

**Comment by YevheniiSemendiak** [comment]
+1 for resolving this issue - a lot of different tools which we are integrating (postgress, mlflow, weights and biasses, etc.) do require it.
In addition to the previous comment, maybe we could inspect the docker image w.r.t. which user is used to run?
