### ISSUE TITLE
Use special roles for service accounts

### ISSUE THREAD

**Issue by romasku** [neuro-inc/neuro-cli#2149]
Currently, user can create a service account for any role it has READ access. This allows to easily generate permanent tokens for pre-existing roles, but has the following downsides as for me:
- Service account role can be deleted directly. This leads to a situation where we still keep track of unusable service account. API already returns "role_deleted" field, but it will not work properly if the role will be recreated.
- Users can create a service token and so a permanent token to their own user role. This can be dangerous from a security perspective.
- I think that there will be a dedicated role created manually for most service accounts. So current approach requires two steps in such cases: the user has to create a role first and then create a service account.
 
 So I propose to disallow the creation of a service account for any existing role and instead generate a special role for service accounts. The user will not have direct access to this role, but he will be able to share any resources to this role (or add it to some group by sharing `role://...` permission). This solves issues from above:
 - Users can not delete service accounts role directly as they have to direct access to it.
 - Roles are created with zero permissions, users have to directly share entities with it.
 - Users have to run only one command `neuro service-account create` instead of `neuro acl add-role username/roles/new-role && neuro service-account create username/roles/new-role`

**Comment by serhiy-storchaka** [comment]
LGTM. If role is created and removed on server side, the user does not need permissions to manage it.

But the server needs to check some user permissions to allow creating and removing of the server account. Maybe `user://{username}/server-accounts +write` or something.
