### ISSUE TITLE
User cannot run the job with the same name on different clusters

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-cli#2442]
#### Description:
Having the user in two clusters, try to run a job with the same name on both clusters.

#### Example:
![image](https://user-images.githubusercontent.com/32543098/143903353-92f95a29-9a56-4fe0-ac4f-0b22558ae1a1.png)

#### Expected behavior:
Users are allowed to run two jobs with the same name.
`neuro status/kill` and other related commands assume the current cluster if no `--cluster` option is provided. 

#### Additional context:
This also related to https://github.com/neuro-inc/neuro-flow/issues/496

**Comment by YevheniiSemendiak** [comment]
cc @johngull

**Comment by asvetlov** [comment]
Sorry. Job name is bound to user by design, not to cluster.
You are requesting for deep structural change.

**Comment by johngull** [comment]
@asvetlov Any chance to make some invisible prefix/postfix to the name using cluster name?

**Comment by asvetlov** [comment]
There is a chance but there is no estimation, sorry.

**Comment by YevheniiSemendiak** [comment]
what if we have a user in the same cluster but in different tenants?

**Comment by YevheniiSemendiak** [comment]
> @asvetlov Any chance to make some invisible prefix/postfix to the name using cluster name?

@johngull , In Neuro-Flow if the job is `multi: True`, we add a suffix to the job name.

**Comment by johngull** [comment]
@YevheniiSemendiak I mean that we can use some extended job name (probably invisible for the customer), which should be unique, and then the same names on different clusters will be allowed.
