### ISSUE TITLE
neuro run works incorrectly with organizations

### ISSUE THREAD

**Issue by eviltwinhans** [neuro-inc/neuro-cli#2562]
### Description
If user is in cluster1(org1), `neuro run ubuntu` should start a job within cluster1(org1).
If user is in cluster1(org1), `neuro run --org NO_ORG ubuntu` should start a job within cluster1(-).
If user is in cluster1(org1), `neuro run --org org2 ubuntu` should start a job within cluster1(org2).

If user is in cluster1(-), `neuro run ubuntu` should start a job within cluster1(-).
If user is in cluster1(-), `neuro run --org NO_ORG ubuntu` should start a job within cluster1(-).
If user is in cluster1(-), `neuro run --org org2 ubuntu` should start a job within cluster1(org2).

### Additionally in the output of `neuro job status`
There's a typo: Organisation -> Organization

**Comment by eviltwinhans** [comment]
https://app.qase.io/case/NEURO-58 is to be run after this issue is done.

**Comment by romasku** [comment]
Fixed on server side: https://github.com/neuro-inc/platform-api/commit/e00518a2946958b49ccaf7934b50047be662a7c8
Deployed to dev

**Comment by eviltwinhans** [comment]
Verified on dev

**Comment by romasku** [comment]
Fixed typo here: https://github.com/neuro-inc/neuro-cli/commit/819ed0012c341ad6305743023d077f9a8f22c16d
