### ISSUE TITLE
Autocompletion does not work for other users storage

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-cli#2584]
#### Example:
1. Get access to someone another user's storage (ask him to share or be the manager)
2. Try to autocomplete `neuro ls storage:/<username>` by pressing TAB button 
3. Observe that nothing happens
4. Try to autocomplete `neuro ls storage://<cluster>/<username>` by pressing TAB button 
5. This one works

#### Expected behavior:
Step 3 also works.

#### Additional context:
Neuro Platform Client 22.1.0

**Comment by asvetlov** [comment]
@serhiy-storchaka please take a look when you have time.
