### ISSUE TITLE
Support Rich 12.x.x

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-cli#2628]
#### Is your feature request related to a problem? Please describe.
Recently, Rich has released a new major version (https://github.com/Textualize/rich/releases/tag/v12.0.0), which broke tests in this package.
We should support it or limit the upper version bound https://github.com/neuro-inc/neuro-cli/blob/master/neuro-cli/setup.cfg#L47

**Comment by asvetlov** [comment]
Tests for *this* package are passed now. 
Rich 12 works fine with neuro-cli.
Closing.
