### ISSUE TITLE
`blob statbucket` should also display bucket endpoint URI

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-cli#2706]
#### Is your feature request related to a problem? Please describe.
If the bucket was imported some time ago, it becomes hard to remember what is the origin of this bucket.

#### Describe the solution you'd like
Having an endpoint URI included in the command `neuro blob statbucket` result will help with that.

#### Additional context
Neuro Platform Client 22.1.3

**Comment by serhiy-storchaka** [comment]
What exactly do you want to get? The value of the `--aws-endpoint-url` option provided in `neuro blob importbucket`?

**Comment by YevheniiSemendiak** [comment]
yes, was talking about this

**Comment by serhiy-storchaka** [comment]
Do we need a special option for this, or display it by default? On my computer it increases the time of `neuro blob statbucket` from 2.5-3 seconds to 4-4.5 seconds.

Should it display also more secret data?

**Comment by YevheniiSemendiak** [comment]
IMO, yes, those are super rare requests. We could move further and add info from `blob du` to this command.
wdyt, @andriihomiak, @anayden ?
