### ISSUE TITLE
`neuro cp --help` doesn't work with `click>=8.1.0`

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-cli#2707]
#### Description:
Due to https://github.com/pallets/click/issues/2149 , our `neuro_cli/utils.py:format_example` isn't working properly and breaks on line: `# download other user's remote file into the current directory`.

#### Additional context:
Neuro Platform Client 22.1.3

The problem arises with `click>=8.1.0`, previous versions, like `click==8.0.4` still work well.

**Comment by serhiy-storchaka** [comment]
I think it is already fixed in the master branch, but not released.
