### ISSUE TITLE
Support projects in URI parsing

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-cli#2956]
As suggested in https://github.com/neuro-inc/neuro-cli/pull/2955, having functions for parsing platform resources URIs, we need to patch and adapt them to support project names.
Part of https://github.com/neuro-inc/no-code/issues/77

https://github.com/neuro-inc/neuro-cli/pull/2960/files#diff-0643a0bc73c408c16b7c497f766bdd264dddaf5767b553720067af7196d75dbfR36

**Comment by andriihomiak** [comment]
@YevheniiSemendiak this seems to be at least somewhat handled in #2960 ([diff](https://github.com/neuro-inc/neuro-cli/pull/2960/files#diff-0643a0bc73c408c16b7c497f766bdd264dddaf5767b553720067af7196d75dbfR14-R37)). Is there something more to do?

**Comment by YevheniiSemendiak** [comment]
some of those places were covered in my PR, others were covered in https://github.com/neuro-inc/neuro-cli/pull/2961
I would suggest double-checking as the last step we did not forget smth.
