### ISSUE TITLE
Cluster manager or admin can only see projects, which they are a part of

### ISSUE THREAD

**Issue by andriihomiak** [neuro-inc/neuro-cli#2989]
#### Description:
Cluster manager or admins should be able to see all of the projects in the cluster, but currently, the output of `neuro admin get-projects <cluster>` is limited to those projects, in which the manager/admin is a member.

#### Example:
1. As some user create a project
```
$ neuro admin add-project default test-project-visibility
Added project test-project-visibility to cluster default. Info:
 Name                test-project-visibility 
 Default role        writer                  
 Is default project  False                   
```
2. As some other cluster manager/admin get all projects in the same cluster:
```
neuro admin get-projects default
```
3. Observe that the `test-project-visibility` is not shown in the output of the command above.

**Comment by YevheniiSemendiak** [comment]
fixed in https://github.com/neuro-inc/platform-admin/pull/873
